### ISSUE TITLE
Sliders reset check marks

### ISSUE THREAD

**Issue by x-chap** [hopkinstechnocrats/FRCScouter#3]
In the end game questions clicking on the box to open the slider clears the checkmarks
before
![](https://i.imgur.com/244IDAm.png)
after
![](https://i.imgur.com/a8cWtt9.png)

**Comment by thisjaiden** [comment]
This issue appears to apply to almost all check boxes and other state on the page. Ex: From autonomous check the checkbox at the top and then enter any map page and come back. Box is unchecked.
