### ISSUE TITLE
In output data, all match numbers are 0

### ISSUE THREAD

**Issue by henryscheible** [hopkinstechnocrats/FRCScouter#5]

**Comment by thisjaiden** [comment]
Will get on this asap. I have some ideas for how the app can be changed to be better before next competition. Make an issue if anything else is irritating or not working as expected. I can't promise to fix match numbers before the end of today but I'll try.

**Comment by thisjaiden** [comment]
Is it still automatically starting matches or is that not working either? @henryscheible

**Comment by thisjaiden** [comment]
tonight I'm going to look into a way to backup the server and load it so that I can manually edit the match numbers tonight. I'll see if I can get it working for tomorrow's matches

**Comment by thisjaiden** [comment]
This was caused by people joining the game in progress instead of waiting in the queue. This will be resolved by removing the queue and replacing it with a manual match number entry.
