### ISSUE TITLE
Where is FRCScouter 2021?

### ISSUE THREAD

**Issue by thisjaiden** [hopkinstechnocrats/FRCScouter#9]
This is more of an announcement than anything else. Due to technical constraints, time restraints, and issues with current spec, FRCScouter is on hiatus. I believe I will come back for the 2022 season with v5, but it's unclear at this time how things will play out. COVID and the removal of cross site cookies have thrown a metaphorical wrench in plans for this project.

I'll keep those interested updated here.

**Comment by herzogjh** [comment]
@thisjaiden We would love to have you back for 2022.  I have some ideas for how to better incorporate the scouting app.
